### ISSUE TITLE
packer build failing with "taskdoc" - missing dependency "supertest"

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#357]
Running through a latest packer build of the Vagrant VM, it's failing when invoking the "taskdoc" processing:

```
    virtualbox-iso: TASK: [remoterepos | Generate hosted task documentation] **********************
    virtualbox-iso: failed: [127.0.0.1] => {"changed": true, "cmd": " npm run taskdoc ", "delta": "0:00:00.565876", "end": "2016-08-01 19:22:18.025979", "item": "", "rc": 1, "start": "2016-08-01 19:22:17.460103"}
    virtualbox-iso: stderr: module.js:327
    virtualbox-iso: throw err;
    virtualbox-iso: ^
    virtualbox-iso:
    virtualbox-iso: Error: Cannot find module 'supertest'
    virtualbox-iso: at Function.Module._resolveFilename (module.js:325:15)
    virtualbox-iso: at Function.Module._load (module.js:276:25)
    virtualbox-iso: at Module.require (module.js:353:17)
    virtualbox-iso: at require (internal/module.js:12:17)
    virtualbox-iso: at Object.<anonymous> (/home/vagrant/src/on-http/node_modules/on-tasks/node_modules/on-core/spec/helper.js:21:18)
    virtualbox-iso: at Module._compile (module.js:409:26)
    virtualbox-iso: at Object.Module._extensions..js (module.js:416:10)
    virtualbox-iso: at Module.load (module.js:343:32)
    virtualbox-iso: at Function.Module._load (module.js:300:12)
    virtualbox-iso: at Module.require (module.js:353:17)
    virtualbox-iso: at require (internal/module.js:12:17)
    virtualbox-iso: at Object.<anonymous> (/home/vagrant/src/on-http/node_modules/on-tasks/task-annotation-generator.js:221:5)
    virtualbox-iso: at Module._compile (module.js:409:26)
    virtualbox-iso: at Object.Module._extensions..js (module.js:416:10)
    virtualbox-iso: at Module.load (module.js:343:32)
    virtualbox-iso: at Function.Module._load (module.js:300:12)
    virtualbox-iso: cat: task_doc_data.json: No such file or directory
    virtualbox-iso: mv: cannot stat './node_modules/on-tasks/task_doc_data.json': No such file or directory
```
